##### dev 配置 #######
spring:
  #数据库配置
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:dm://localhost:5236
          username: BIANMU
          password: 123456789
          driver-class-name: dm.jdbc.driver.DmDriver

  thymeleaf:
    # 页面缓存配置
    cache: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl