server:
  port: 8888
  servlet:
    context-path: /oauth-server

spring:
  application:
    name: oauth-server
  profiles:
    active: prod #选择配置分支，先读取系统环境变量，如果没有则默认值为 prod


  #mvc接收参数时对日期进行格式化
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss