##### dev 配置 #######
oauth:
  server: http://localhost:8888/oauth-server

spring:
  #数据库配置
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:dm://127.0.0.1:5236
          username: BIANMU
          password: 123456789
          driver-class-name: dm.jdbc.driver.DmDriver
  # 页面缓存
  thymeleaf:
    cache: false

  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200

security:
  oauth2:
    client:
      client-id: bianmu
      client-secret: bianmu_123456
      access-token-uri: ${oauth.server}/oauth/token
      user-authorization-uri: ${oauth.server}/oauth/authorize
    resource:
      user-info-uri: ${oauth.server}/oauth/user/info

project:
  #是否需要输入验证码
  captcha-enable: false
  # 是否启用记住我（免登录，debug利器）
  remember-me-enable: true
  # 配置文件存储方式
  file-storage:
    # 存储路径
    path: ${user.home}/shandan/bianmu/upload