##### prod 配置 #######
server:
  port: 18000

spring:
  #数据库配置
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:dm://172.16.36.240:5236
          username: BIANMU
          password: admin1234
          driver-class-name: dm.jdbc.driver.DmDriver

oauth:
  server: http://localhost:8888/oauth-server
security:
  oauth2:
    client:
      client-id: desktop
      client-secret: bianmu_123456
      access-token-uri: ${oauth.server}/oauth/token
      user-authorization-uri: ${oauth.server}/oauth/authorize
    resource:
      user-info-uri: ${oauth.server}/oauth/user/info
