##### 生产环境配置 #######
spring:
#  profiles:
#    active: prod

  datasource:
    url: jdbc:dm://localhost:5236
    username: BIANMU
    password: 123456789
    driver-class-name: dm.jdbc.driver.DmDriver

bianmu:
  #是否需要输入验证码
  captcha-enable: false
  # 配置文件存储方式
  file-storage:
    # 存储位置，local：本地，nas：NAS存储服务
    location: local
    # 存储路径
    path: D:/BIANMU/