CREATE TABLE "BIANMU"."SYS_USER_ROLE"
(
 "USER_ROLE_ID" VARCHAR(50) NOT NULL,
 "USER_ID" VARCHAR2(50) NOT NULL,
 "ROLE_ID" VARCHAR2(50) NOT NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "MODIFY_TIME" TIMESTAMP(0) NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL
);

CREATE TABLE "BIANMU"."SYS_USER"
(
 "USER_ID" VARCHAR(50) NOT NULL,
 "LOGIN_NAME" VARCHAR2(50) NOT NULL,
 "USER_NAME" VARCHAR2(50) NOT NULL,
 "PASSWORD" VARCHAR2(50) NOT NULL,
 "VALID" CHAR(1) DEFAULT 1
 NOT NULL,
 "LIMITED_IP" VARCHAR2(50) NULL,
 "EXPIRED_TIME" TIMESTAMP(6) NULL,
 "LAST_CHANGE_PWD_TIME" TIMESTAMP(6) NULL,
 "LIMIT_MULTI_LOGIN" CHAR(1) DEFAULT 1
 NULL,
 "CREATE_TIME" TIMESTAMP(6) NULL,
 "MODIFY_TIME" TIMESTAMP(6) NULL,
 "ORG_ID" VARCHAR2(50) NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL,
 "IS_DELETE" CHAR(1) DEFAULT 0
 NULL
);

CREATE TABLE "BIANMU"."SYS_SHORTCUT_MENU"
(
 "SHORTCUT_MENU_ID" VARCHAR(255) NOT NULL,
 "SHORTCUT_MENU_NAME" VARCHAR2(50) NOT NULL,
 "SHORTCUT_MENU_PATH" VARCHAR2(50) NOT NULL,
 "USER_ID" VARCHAR2(50) NOT NULL,
 "SHORTCUT_MENU_PARENT_ID" VARCHAR2(50) NULL,
 "SORT_WEIGHT" NUMBER(6,0) NULL,
 "CREATE_TIME" TIMESTAMP(0) NOT NULL,
 "MODIFY_TIME" TIMESTAMP(0) NOT NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL
);

CREATE TABLE "BIANMU"."SYS_SETTING"
(
 "ID" VARCHAR(50) NOT NULL,
 "SYS_NAME" VARCHAR2(50) NULL,
 "SYS_LOGO" VARCHAR2(150) NULL,
 "SYS_BOTTOM_TEXT" VARCHAR2(100) NULL,
 "SYS_NOTICE_TEXT" CLOB NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "MODIFY_TIME" TIMESTAMP(0) NULL,
 "USER_INIT_PASSWORD" VARCHAR2(50) NULL,
 "SYS_COLOR" VARCHAR2(50) NULL,
 "SYS_API_ENCRYPT" CHAR(1) NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL
);

CREATE TABLE "BIANMU"."SYS_ROLE_PERMISSIONS"
(
 "RP_ID" VARCHAR(50) NOT NULL,
 "ROLE_ID" VARCHAR2(50) NULL,
 "PERMIS_ID" VARCHAR2(50) NULL,
 "CREATE_TIME" TIMESTAMP(6) NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "MODIFY_TIME" TIMESTAMP(6) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL,
  CLUSTER PRIMARY KEY("RP_ID") ENABLE 
);

CREATE TABLE "BIANMU"."SYS_ROLE_MENU"
(
 "RM_ID" VARCHAR(50) NOT NULL,
 "ROLE_ID" VARCHAR2(50) NULL,
 "MENU_ID" VARCHAR2(50) NULL,
 "CREATE_TIME" TIMESTAMP(6) NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "MODIFY_TIME" TIMESTAMP(6) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL,
  CLUSTER PRIMARY KEY("RM_ID") ENABLE 
);

CREATE TABLE "BIANMU"."SYS_ROLE"
(
 "ROLE_ID" VARCHAR(50) NOT NULL,
 "ROLE_NAME" VARCHAR2(50) NOT NULL,
 "ROLE_REMARK" VARCHAR2(200) NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "MODIFY_TIME" TIMESTAMP(0) NULL,
 "ROLE_CONTENT" VARCHAR2(50) NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL
);

CREATE TABLE "BIANMU"."SYS_PERMISSIONS"
(
 "PERMIS_ID" VARCHAR(50) NOT NULL,
 "PERMIS_NAME" VARCHAR2(50) NOT NULL,
 "PERMIS_REMARK" VARCHAR2(200) NULL,
 "PERMIS_SCOPE" VARCHAR2(50) NOT NULL,
 "HAS_SELECT" CHAR(1) DEFAULT 1
 NULL,
 "HAS_ADD" CHAR(1) DEFAULT 0
 NULL,
 "HAS_EDIT" CHAR(1) DEFAULT 0
 NULL,
 "HAS_DELETE" CHAR(1) DEFAULT 0
 NULL,
 "CREATE_TIME" TIMESTAMP(6) NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "MODIFY_TIME" TIMESTAMP(6) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL,
  CLUSTER PRIMARY KEY("PERMIS_ID") ENABLE 
);

CREATE TABLE "BIANMU"."SYS_ORG"
(
 "ID" VARCHAR(50) NOT NULL,
 "ORG_NUMBER" VARCHAR2(50) NULL,
 "ORG_NAME" VARCHAR2(50) NULL,
 "ORG_SHORT_NAME" VARCHAR2(50) NULL,
 "ORG_PARENT_ID" VARCHAR2(50) NULL,
 "ORG_PATH" VARCHAR2(50) NULL,
 "LEADER" VARCHAR2(50) NULL,
 "REMARK" VARCHAR2(50) NULL,
 "SORT" NUMBER(6,0) NULL,
 "IS_DELETE" CHAR(1) DEFAULT 0
 NULL,
 "CREATE_TIME" TIMESTAMP(6) NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "MODIFY_TIME" TIMESTAMP(6) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL,
 "ORG_PARENT_NAME" VARCHAR2(50) NULL,
 "LEADER_NAME" VARCHAR2(50) NULL,
  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "BIANMU"."SYS_NOTIFICATION_UNREAD"
(
 "ID" VARCHAR2(50) NOT NULL,
 "USER_ID" VARCHAR2(50) NOT NULL,
 "NOTIFICATION_ID" VARCHAR2(50) NOT NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "CREATE_TIME" TIMESTAMP(6) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL,
 "MODIFY_TIME" TIMESTAMP(6) NULL,
  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "BIANMU"."SYS_NOTIFICATION"
(
 "ID" VARCHAR2(50) NOT NULL,
 "FROM_ID" VARCHAR2(50) NOT NULL,
 "RECEIVE_ID" VARCHAR2(2000) NOT NULL,
 "TITLE" VARCHAR2(150) NOT NULL,
 "CONTENT" VARCHAR2(1500) NOT NULL,
 "TYPE" VARCHAR2(50) DEFAULT 'NORMAL'
 NOT NULL,
 "ALL_READ" CHAR(10) NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "CREATE_TIME" TIMESTAMP(6) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL,
 "MODIFY_TIME" TIMESTAMP(6) NULL,
  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "BIANMU"."SYS_MENU"
(
 "MENU_ID" VARCHAR(50) NOT NULL,
 "MENU_NAME" VARCHAR2(50) NOT NULL,
 "MENU_PATH" VARCHAR2(50) NOT NULL,
 "MENU_PARENT_ID" VARCHAR2(50) NULL,
 "SORT_WEIGHT" NUMBER(6,0) DEFAULT 0
 NULL,
 "CREATE_TIME" TIMESTAMP(0) NOT NULL,
 "MODIFY_TIME" TIMESTAMP(0) NOT NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL,
 "IS_DELETE" CHAR(1) DEFAULT '0'
 NULL
);

CREATE TABLE "BIANMU"."SYS_FILE"
(
 "ID" VARCHAR2(50) NOT NULL,
 "ENTITY_ID" VARCHAR2(50) NULL,
 "FILE_NAME" VARCHAR2(150) NOT NULL,
 "FILE_SUFFIX" VARCHAR2(10) NULL,
 "FILE_TYPE" VARCHAR2(10) NULL,
 "FILE_SIZE" NUMBER(12,6) NOT NULL,
 "LOCATION" VARCHAR2(10) NOT NULL,
 "PATH" VARCHAR2(200) NOT NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "CREATE_TIME" TIMESTAMP(6) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL,
 "MODIFY_TIME" TIMESTAMP(6) NULL,
  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "BIANMU"."PERSISTENT_LOGINS"
(
 "SERIES" VARCHAR2(50) NOT NULL,
 "USERNAME" VARCHAR2(50) NOT NULL,
 "TOKEN" VARCHAR2(50) NOT NULL,
 "LAST_USED" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL
);

CREATE TABLE "BIANMU"."B_REVIEW_RECORD"
(
 "ID" VARCHAR2(50) NULL,
 "ENTITY_ID" VARCHAR2(50) NULL,
 "ENTITY_TYPE" VARCHAR2(15) NULL,
 "REVIEW_OPERATE" VARCHAR2(20) NULL,
 "REVIEW_OPINION" VARCHAR2(500) NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "CREATE_TIME" TIMESTAMP(6) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL,
 "MODIFY_TIME" TIMESTAMP(6) NULL,
 "ORG_ID" VARCHAR2(50) NULL
);

CREATE TABLE "BIANMU"."B_METADATA_DETAILS"
(
 "ID" VARCHAR(50) NOT NULL,
 "METADATA_ID" VARCHAR(50) NULL,
 "TABLE_NAME" VARCHAR2(50) NULL,
 "MASTER" CHAR(1) DEFAULT 0
 NULL,
 "TABLE_COMMENT" VARCHAR2(50) NULL,
 "TABLE_PRIMARY_COLUMN" VARCHAR2(50) NULL,
 "TABLE_COLUMNS" TEXT NULL,
 "FOREIGN_TABLE" VARCHAR2(50) NULL,
 "FOREIGN_COLUMN" VARCHAR2(50) NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "CREATE_TIME" TIMESTAMP(6) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL,
 "MODIFY_TIME" TIMESTAMP(6) NULL
);

CREATE TABLE "BIANMU"."B_METADATA_BASIC"
(
 "ID" VARCHAR(50) NOT NULL,
 "DATA_SOURCE_ID" VARCHAR(50) NULL,
 "METADATA_NAME" VARCHAR2(50) NULL,
 "METADATA_COMMENT" VARCHAR2(250) NULL,
 "DATA_FROM" VARCHAR2(50) NULL,
 "DATA_TYPE" VARCHAR2(50) NULL,
 "SECRET_LEVEL" VARCHAR2(50) NULL,
 "COLLECTION_TIME" TIMESTAMP(6) NULL,
 "THEME_TASK" VARCHAR2(50) NULL,
 "REVIEW_STATUS" VARCHAR2(20) DEFAULT 'UN_SUBMIT'
 NULL,
 "ORG_ID" VARCHAR2(50) NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "CREATE_TIME" TIMESTAMP(6) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL,
 "MODIFY_TIME" TIMESTAMP(6) NULL,
  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "BIANMU"."B_DIRECTORY_METADATA"
(
 "ID" VARCHAR2(50) NOT NULL,
 "DIRECTORY_ID" VARCHAR2(50) NOT NULL,
 "METADATA_ID" VARCHAR2(50) NOT NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "CREATE_TIME" TIMESTAMP(6) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL,
 "MODIFY_TIME" TIMESTAMP(6) NULL,
  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "BIANMU"."B_DIRECTORY"
(
 "ID" VARCHAR2(50) NOT NULL,
 "DIRECTORY_NAME" VARCHAR2(150) NOT NULL,
 "PARENT_ID" VARCHAR2(50) NULL,
 "REVIEW_STATUS" VARCHAR2(20) DEFAULT 'UN_SUBMIT'
 NULL,
 "ORG_ID" VARCHAR2(50) NULL,
 "CREATE_USER" VARCHAR2(50) NULL,
 "CREATE_TIME" TIMESTAMP(6) NULL,
 "MODIFY_USER" VARCHAR2(50) NULL,
 "MODIFY_TIME" TIMESTAMP(6) NULL,
 "DIRECTORY_TYPE" VARCHAR2(15) NULL,
 "DIRECTORY_PATH" VARCHAR2(350) NULL,
  CLUSTER PRIMARY KEY("ID") ENABLE 
);

CREATE TABLE "BIANMU"."B_DATA_SOURCE"
(
 "ID" VARCHAR(50) NOT NULL,
 "NAME" VARCHAR2(50) NULL,
 "TYPE" CHAR(1) NULL,
 "DB_TYPE" VARCHAR2(50) NULL,
 "DB_VERSION" VARCHAR2(50) NULL,
 "JDBC_DRIVER_CLASS" VARCHAR2(200) NULL,
 "JDBC_URL" VARCHAR2(200) NULL,
 "JDBC_USER_NAME" VARCHAR2(50) NULL,
 "JDBC_PASSWORD" VARCHAR2(50) NULL,
 "JDBC_SCHEMA" VARCHAR2(50) NULL,
 "HOST" VARCHAR2(50) NULL,
 "PORT" NUMBER(5,0) NULL,
 "REMARK" VARCHAR2(500) NULL,
 "IS_DELETE" CHAR(1) DEFAULT 0
 NULL,
 "CREATE_TIME" TIMESTAMP(6) NULL,
 "MODIFY_TIME" TIMESTAMP(6) NULL,
 "CREATE_USER" VARCHAR(50) NULL,
 "MODIFY_USER" VARCHAR(50) NULL,
  CLUSTER PRIMARY KEY("ID") ENABLE 
);

ALTER TABLE "BIANMU"."SYS_USER_ROLE" ADD CONSTRAINT  PRIMARY KEY("USER_ROLE_ID") ;

ALTER TABLE "BIANMU"."SYS_USER" ADD CONSTRAINT  PRIMARY KEY("USER_ID") ;

ALTER TABLE "BIANMU"."SYS_SHORTCUT_MENU" ADD CONSTRAINT  PRIMARY KEY("SHORTCUT_MENU_ID") ;

ALTER TABLE "BIANMU"."SYS_SETTING" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "BIANMU"."SYS_ROLE" ADD CONSTRAINT  PRIMARY KEY("ROLE_ID") ;

ALTER TABLE "BIANMU"."SYS_ORG" ADD CONSTRAINT "CONS134218775" UNIQUE("ORG_NUMBER") ;

ALTER TABLE "BIANMU"."SYS_MENU" ADD CONSTRAINT  PRIMARY KEY("MENU_ID") ;

ALTER TABLE "BIANMU"."B_METADATA_DETAILS" ADD CONSTRAINT  PRIMARY KEY("ID") ;

COMMENT ON TABLE "BIANMU"."SYS_USER_ROLE" IS '系统用户角色关系表';

COMMENT ON COLUMN "BIANMU"."SYS_USER_ROLE"."USER_ROLE_ID" IS '关系主键';

COMMENT ON COLUMN "BIANMU"."SYS_USER_ROLE"."USER_ID" IS '用户ID';

COMMENT ON COLUMN "BIANMU"."SYS_USER_ROLE"."ROLE_ID" IS '角色ID';

COMMENT ON COLUMN "BIANMU"."SYS_USER_ROLE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."SYS_USER_ROLE"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "BIANMU"."SYS_USER_ROLE"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."SYS_USER_ROLE"."MODIFY_USER" IS '修改用户';

CREATE UNIQUE INDEX "INDEX31481468347887"
ON "BIANMU"."SYS_USER"("USER_ID");

COMMENT ON TABLE "BIANMU"."SYS_USER" IS '系统用户表';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."USER_ID" IS '用户id';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."LOGIN_NAME" IS '登录名';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."USER_NAME" IS '用户名称';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."PASSWORD" IS '登录密码';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."VALID" IS '是否允许登录系统（0：不允许，1：允许）';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."LIMITED_IP" IS '限制允许登录的IP集合';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."EXPIRED_TIME" IS '账号失效时间，超过时间将不能登录系统';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."LAST_CHANGE_PWD_TIME" IS '最近修改密码时间，超出时间间隔，提示用户修改密码';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."LIMIT_MULTI_LOGIN" IS '是否允许账号同一个时刻多人在线，（0：不允许，1：允许）';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."ORG_ID" IS '组织机构ID';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."MODIFY_USER" IS '修改用户';

COMMENT ON COLUMN "BIANMU"."SYS_USER"."IS_DELETE" IS '是否删除（0：未删除，1：已删除）';

CREATE UNIQUE INDEX "INDEX31130075251892"
ON "BIANMU"."SYS_SHORTCUT_MENU"("SHORTCUT_MENU_ID");

COMMENT ON TABLE "BIANMU"."SYS_SHORTCUT_MENU" IS '用户快捷菜单表';

COMMENT ON COLUMN "BIANMU"."SYS_SHORTCUT_MENU"."SHORTCUT_MENU_ID" IS '用户快捷菜单id';

COMMENT ON COLUMN "BIANMU"."SYS_SHORTCUT_MENU"."SHORTCUT_MENU_NAME" IS '用户快捷菜单名称';

COMMENT ON COLUMN "BIANMU"."SYS_SHORTCUT_MENU"."SHORTCUT_MENU_PATH" IS '用户快捷菜单路径';

COMMENT ON COLUMN "BIANMU"."SYS_SHORTCUT_MENU"."USER_ID" IS '用户id';

COMMENT ON COLUMN "BIANMU"."SYS_SHORTCUT_MENU"."SHORTCUT_MENU_PARENT_ID" IS '上级id';

COMMENT ON COLUMN "BIANMU"."SYS_SHORTCUT_MENU"."SORT_WEIGHT" IS '同级排序权重';

COMMENT ON COLUMN "BIANMU"."SYS_SHORTCUT_MENU"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."SYS_SHORTCUT_MENU"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "BIANMU"."SYS_SHORTCUT_MENU"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."SYS_SHORTCUT_MENU"."MODIFY_USER" IS '修改用户';

CREATE UNIQUE INDEX "INDEX31130097574959"
ON "BIANMU"."SYS_SETTING"("ID");

COMMENT ON TABLE "BIANMU"."SYS_SETTING" IS '系统设置表';

COMMENT ON COLUMN "BIANMU"."SYS_SETTING"."ID" IS '表id';

COMMENT ON COLUMN "BIANMU"."SYS_SETTING"."SYS_NAME" IS '系统名称';

COMMENT ON COLUMN "BIANMU"."SYS_SETTING"."SYS_LOGO" IS '系统logo图标';

COMMENT ON COLUMN "BIANMU"."SYS_SETTING"."SYS_BOTTOM_TEXT" IS '系统底部信息';

COMMENT ON COLUMN "BIANMU"."SYS_SETTING"."SYS_NOTICE_TEXT" IS '系统公告';

COMMENT ON COLUMN "BIANMU"."SYS_SETTING"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."SYS_SETTING"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "BIANMU"."SYS_SETTING"."USER_INIT_PASSWORD" IS '用户管理：初始、重置密码';

COMMENT ON COLUMN "BIANMU"."SYS_SETTING"."SYS_COLOR" IS '系统颜色';

COMMENT ON COLUMN "BIANMU"."SYS_SETTING"."SYS_API_ENCRYPT" IS 'API加密 Y/N';

COMMENT ON COLUMN "BIANMU"."SYS_SETTING"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."SYS_SETTING"."MODIFY_USER" IS '修改用户';

COMMENT ON TABLE "BIANMU"."SYS_ROLE_PERMISSIONS" IS '系统角色与权限关系表';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE_PERMISSIONS"."RP_ID" IS '主键';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE_PERMISSIONS"."ROLE_ID" IS '角色ID';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE_PERMISSIONS"."PERMIS_ID" IS '权限ID';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE_PERMISSIONS"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE_PERMISSIONS"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE_PERMISSIONS"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE_PERMISSIONS"."MODIFY_USER" IS '修改用户';

COMMENT ON TABLE "BIANMU"."SYS_ROLE_MENU" IS '系统角色菜单关系表';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE_MENU"."RM_ID" IS '主键';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE_MENU"."ROLE_ID" IS '角色ID';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE_MENU"."MENU_ID" IS '菜单ID';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE_MENU"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE_MENU"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE_MENU"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE_MENU"."MODIFY_USER" IS '修改用户';

COMMENT ON TABLE "BIANMU"."SYS_ROLE" IS '系统角色表';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE"."ROLE_ID" IS '角色ID';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE"."ROLE_NAME" IS '角色名称';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE"."ROLE_REMARK" IS '角色描述';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE"."ROLE_CONTENT" IS '权限内容';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."SYS_ROLE"."MODIFY_USER" IS '修改用户';

COMMENT ON TABLE "BIANMU"."SYS_PERMISSIONS" IS '系统权限表';

COMMENT ON COLUMN "BIANMU"."SYS_PERMISSIONS"."PERMIS_ID" IS '权限ID';

COMMENT ON COLUMN "BIANMU"."SYS_PERMISSIONS"."PERMIS_NAME" IS '权限名称';

COMMENT ON COLUMN "BIANMU"."SYS_PERMISSIONS"."PERMIS_REMARK" IS '权限描述';

COMMENT ON COLUMN "BIANMU"."SYS_PERMISSIONS"."PERMIS_SCOPE" IS '数据权限范围';

COMMENT ON COLUMN "BIANMU"."SYS_PERMISSIONS"."HAS_SELECT" IS '查询权限（0：无权限，1：有权限）';

COMMENT ON COLUMN "BIANMU"."SYS_PERMISSIONS"."HAS_ADD" IS '新增权限（0：无权限，1：有权限）';

COMMENT ON COLUMN "BIANMU"."SYS_PERMISSIONS"."HAS_EDIT" IS '编辑权限（0：无权限，1：有权限）';

COMMENT ON COLUMN "BIANMU"."SYS_PERMISSIONS"."HAS_DELETE" IS '删除权限（0：无权限，1：有权限）';

COMMENT ON COLUMN "BIANMU"."SYS_PERMISSIONS"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."SYS_PERMISSIONS"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."SYS_PERMISSIONS"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "BIANMU"."SYS_PERMISSIONS"."MODIFY_USER" IS '修改用户';

COMMENT ON TABLE "BIANMU"."SYS_ORG" IS '组织机构表';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."ID" IS '主键';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."ORG_NUMBER" IS '机构编号';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."ORG_NAME" IS '机构名称';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."ORG_SHORT_NAME" IS '机构简称';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."ORG_PARENT_ID" IS '父机构ID';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."ORG_PATH" IS '机构路径';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."LEADER" IS '机构负责人';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."REMARK" IS '机构描述';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."SORT" IS '排列顺序';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."IS_DELETE" IS '是否删除（0：未删除，1：已删除）';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."MODIFY_USER" IS '修改用户';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."ORG_PARENT_NAME" IS '父机构名称';

COMMENT ON COLUMN "BIANMU"."SYS_ORG"."LEADER_NAME" IS '机构负责人名称';

COMMENT ON TABLE "BIANMU"."SYS_NOTIFICATION_UNREAD" IS '系统通知未读表';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION_UNREAD"."ID" IS '主键';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION_UNREAD"."USER_ID" IS '用户ID';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION_UNREAD"."NOTIFICATION_ID" IS '系统通知ID';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION_UNREAD"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION_UNREAD"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION_UNREAD"."MODIFY_USER" IS '修改用户';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION_UNREAD"."MODIFY_TIME" IS '修改时间';

COMMENT ON TABLE "BIANMU"."SYS_NOTIFICATION" IS '系统通知表';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION"."ID" IS '主键ID';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION"."FROM_ID" IS '发送人ID';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION"."RECEIVE_ID" IS '接收人ID，多个接收人ID使用`,`拼接，最多40人';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION"."TITLE" IS '通知标题';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION"."CONTENT" IS '通知内容，纯汉字内容最大不超过500个字符';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION"."TYPE" IS '通知类型，NORMAL:普通通知（默认），METADATA_REVIEW:元数据审核，DIRECTORY_REVIEW:目录审核';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION"."ALL_READ" IS '全部已读';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION"."MODIFY_USER" IS '修改用户';

COMMENT ON COLUMN "BIANMU"."SYS_NOTIFICATION"."MODIFY_TIME" IS '修改时间';

CREATE UNIQUE INDEX "INDEX31130120415298"
ON "BIANMU"."SYS_MENU"("MENU_ID");

COMMENT ON TABLE "BIANMU"."SYS_MENU" IS '系统菜单表';

COMMENT ON COLUMN "BIANMU"."SYS_MENU"."MENU_ID" IS '菜单id';

COMMENT ON COLUMN "BIANMU"."SYS_MENU"."MENU_NAME" IS '菜单名称';

COMMENT ON COLUMN "BIANMU"."SYS_MENU"."MENU_PATH" IS '菜单路径';

COMMENT ON COLUMN "BIANMU"."SYS_MENU"."MENU_PARENT_ID" IS '上级id';

COMMENT ON COLUMN "BIANMU"."SYS_MENU"."SORT_WEIGHT" IS '同级排序权重';

COMMENT ON COLUMN "BIANMU"."SYS_MENU"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."SYS_MENU"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "BIANMU"."SYS_MENU"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."SYS_MENU"."MODIFY_USER" IS '修改用户';

COMMENT ON COLUMN "BIANMU"."SYS_MENU"."IS_DELETE" IS '逻辑删除，0:未删除，1:已删除';

COMMENT ON TABLE "BIANMU"."SYS_FILE" IS '系统文件表';

COMMENT ON COLUMN "BIANMU"."SYS_FILE"."ID" IS '主键ID';

COMMENT ON COLUMN "BIANMU"."SYS_FILE"."ENTITY_ID" IS '实体对象ID';

COMMENT ON COLUMN "BIANMU"."SYS_FILE"."FILE_NAME" IS '文件名称';

COMMENT ON COLUMN "BIANMU"."SYS_FILE"."FILE_SUFFIX" IS '文件后缀';

COMMENT ON COLUMN "BIANMU"."SYS_FILE"."FILE_TYPE" IS '文件类型';

COMMENT ON COLUMN "BIANMU"."SYS_FILE"."FILE_SIZE" IS '文件大小（单位：MB）';

COMMENT ON COLUMN "BIANMU"."SYS_FILE"."LOCATION" IS '存储位置（local：本地存储，nas：NAS存储）';

COMMENT ON COLUMN "BIANMU"."SYS_FILE"."PATH" IS '存储路径';

COMMENT ON COLUMN "BIANMU"."SYS_FILE"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."SYS_FILE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."SYS_FILE"."MODIFY_USER" IS '修改用户';

COMMENT ON COLUMN "BIANMU"."SYS_FILE"."MODIFY_TIME" IS '修改时间';

CREATE UNIQUE INDEX "INDEX31130153725535"
ON "BIANMU"."PERSISTENT_LOGINS"("SERIES");

COMMENT ON TABLE "BIANMU"."PERSISTENT_LOGINS" IS 'persistent_logins表，用户实现记住我功能';

COMMENT ON COLUMN "BIANMU"."PERSISTENT_LOGINS"."SERIES" IS 'id';

COMMENT ON COLUMN "BIANMU"."PERSISTENT_LOGINS"."USERNAME" IS '登陆账号';

COMMENT ON COLUMN "BIANMU"."PERSISTENT_LOGINS"."TOKEN" IS 'cookie令牌';

COMMENT ON COLUMN "BIANMU"."PERSISTENT_LOGINS"."LAST_USED" IS '最后更新时间';

COMMENT ON TABLE "BIANMU"."B_REVIEW_RECORD" IS '审核记录表';

COMMENT ON COLUMN "BIANMU"."B_REVIEW_RECORD"."ID" IS '主键';

COMMENT ON COLUMN "BIANMU"."B_REVIEW_RECORD"."ENTITY_ID" IS '数据实体ID';

COMMENT ON COLUMN "BIANMU"."B_REVIEW_RECORD"."ENTITY_TYPE" IS '数据实体类型（"DIRECTORY"：目录，"METADATA"：元数据）';

COMMENT ON COLUMN "BIANMU"."B_REVIEW_RECORD"."REVIEW_OPERATE" IS '审核操作（"SUBMIT"：提交审核，"REVIEW_PASS"：审核通过， "REVIEW_FAIL"：审核不通过）';

COMMENT ON COLUMN "BIANMU"."B_REVIEW_RECORD"."REVIEW_OPINION" IS '审核意见';

COMMENT ON COLUMN "BIANMU"."B_REVIEW_RECORD"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."B_REVIEW_RECORD"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."B_REVIEW_RECORD"."MODIFY_USER" IS '修改用户';

COMMENT ON COLUMN "BIANMU"."B_REVIEW_RECORD"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "BIANMU"."B_REVIEW_RECORD"."ORG_ID" IS '所属机构ID';

COMMENT ON TABLE "BIANMU"."B_METADATA_DETAILS" IS '元数据详情表';

COMMENT ON COLUMN "BIANMU"."B_METADATA_DETAILS"."ID" IS '主键';

COMMENT ON COLUMN "BIANMU"."B_METADATA_DETAILS"."METADATA_ID" IS '元数据ID';

COMMENT ON COLUMN "BIANMU"."B_METADATA_DETAILS"."TABLE_NAME" IS '数据表名称';

COMMENT ON COLUMN "BIANMU"."B_METADATA_DETAILS"."MASTER" IS '是否主表 （1：是，0：否）';

COMMENT ON COLUMN "BIANMU"."B_METADATA_DETAILS"."TABLE_COMMENT" IS '数据表注释';

COMMENT ON COLUMN "BIANMU"."B_METADATA_DETAILS"."TABLE_PRIMARY_COLUMN" IS '数据表主键列';

COMMENT ON COLUMN "BIANMU"."B_METADATA_DETAILS"."TABLE_COLUMNS" IS '数据表字段';

COMMENT ON COLUMN "BIANMU"."B_METADATA_DETAILS"."FOREIGN_TABLE" IS '关联的外表';

COMMENT ON COLUMN "BIANMU"."B_METADATA_DETAILS"."FOREIGN_COLUMN" IS '外表的外键';

COMMENT ON COLUMN "BIANMU"."B_METADATA_DETAILS"."CREATE_USER" IS '创建人';

COMMENT ON COLUMN "BIANMU"."B_METADATA_DETAILS"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."B_METADATA_DETAILS"."MODIFY_USER" IS '修改人';

COMMENT ON COLUMN "BIANMU"."B_METADATA_DETAILS"."MODIFY_TIME" IS '修改时间';

COMMENT ON TABLE "BIANMU"."B_METADATA_BASIC" IS '元数据表';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."ID" IS '主键';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."DATA_SOURCE_ID" IS '数据源表ID';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."METADATA_NAME" IS '元数据名称';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."METADATA_COMMENT" IS '元数据表中文注释';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."DATA_FROM" IS '数据来源';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."DATA_TYPE" IS '数据类型';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."SECRET_LEVEL" IS '数据密级';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."COLLECTION_TIME" IS '采集时间';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."THEME_TASK" IS '主题任务';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."REVIEW_STATUS" IS '数据审核状态（''UN_SUBMIT''：未提交，''SUBMITTED''：已提交，''PASS''：审核通过，''FAIL''：审核未通过）';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."ORG_ID" IS '所属机构ID';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."CREATE_USER" IS '创建人';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."MODIFY_USER" IS '修改人';

COMMENT ON COLUMN "BIANMU"."B_METADATA_BASIC"."MODIFY_TIME" IS '修改时间';

COMMENT ON TABLE "BIANMU"."B_DIRECTORY_METADATA" IS '目录与元数据关系表';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY_METADATA"."ID" IS '主键';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY_METADATA"."DIRECTORY_ID" IS '目录ID';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY_METADATA"."METADATA_ID" IS '元数据ID';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY_METADATA"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY_METADATA"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY_METADATA"."MODIFY_USER" IS '修改用户';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY_METADATA"."MODIFY_TIME" IS '修改时间';

COMMENT ON TABLE "BIANMU"."B_DIRECTORY" IS '目录表';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY"."ID" IS '主键';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY"."DIRECTORY_NAME" IS '目录名称';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY"."PARENT_ID" IS '父目录ID';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY"."REVIEW_STATUS" IS '数据审核状态（''UN_SUBMIT''：未提交，''SUBMITTED''：已提交，''PASS''：审核通过，''FAIL''：审核未通过）';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY"."ORG_ID" IS '所属机构ID';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY"."MODIFY_USER" IS '修改用户';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY"."DIRECTORY_TYPE" IS '目录类型（''DIRECTORY''：结构目录，''METADATA''：元数据目录）';

COMMENT ON COLUMN "BIANMU"."B_DIRECTORY"."DIRECTORY_PATH" IS '目录路径，由父级目录拼接而成（\***\***\***）';

COMMENT ON TABLE "BIANMU"."B_DATA_SOURCE" IS '数据源表';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."ID" IS '主键';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."NAME" IS '数据源名称';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."TYPE" IS '数据源类型(0：关系型数据库，1：非关系型数据库，2：文件存储)';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."DB_TYPE" IS '数据库类型(ORACLE、MYSQL、DM、SQLSERVER等)';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."DB_VERSION" IS '数据库版本';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."JDBC_DRIVER_CLASS" IS 'JDBC数据库驱动';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."JDBC_URL" IS 'JDBC数据库连接';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."JDBC_USER_NAME" IS 'JDBC数据库用户名';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."JDBC_PASSWORD" IS 'JDBC数据库密码';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."JDBC_SCHEMA" IS 'JDBC数据库模式';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."HOST" IS '主机';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."PORT" IS '端口';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."REMARK" IS '描述';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."IS_DELETE" IS '是否删除（0：存在，1：已删除）';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "BIANMU"."B_DATA_SOURCE"."MODIFY_USER" IS '修改用户';

